<a href="https://colab.research.google.com/github/yajuna/tmath308/blob/master/lab0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 0: Introduction to Python

Welcome to Python lab! In these exercises, we will learn some basic commands in Python. A couple of these exercises are mentioned in class.

In [ ]:
# import numpy and scipy for numerical and scientific computations; import visualization tool
import numpy as np
import scipy as sp

# visualization tools
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from typing import Tuple, Iterable

# We have looked at this system in class

\begin{align}
3x_1+2x_2+x_3=1\\
-x_1+x_2+5x_3=2\\
2x_1-3x_2=3\\
x_2+x_3=4\end{align}
and know that it has no **exact** solutions. In this part of the lab, we study the least square solution to it.

In [ ]:
# define coefficient matrix and right hand side

B = np.array([[3,2,1],[-1,1,5],[2,-3,0],[0,1,1]])
b = np.array([[1],[2],[3],[4]])

# type print(B,b) to print the above variables
print(B,b)

[[ 3  2  1]
 [-1  1  5]
 [ 2 -3  0]
 [ 0  1  1]] [[1]
 [2]
 [3]
 [4]]


The python command x = np.linalg.lstsq(B,b) computes the least square solution of the system $Bx=b$. Bye that we mean the $x$ such that the difference $Bx-b$ is the smallest in some sense (the 2-norm).

In [ ]:
# type in the command x = np.linalg.lstsq(B,b, rcond = None) and then type print(x) to see the output

x = np.linalg.lstsq(B,b, rcond = None)
print(x)

(array([[ 0.57342657],
       [-0.41258741],
       [ 0.72027972]]), array([14.76923077]), 3, array([5.59367481, 3.70281003, 3.31662479]))


You probably have noticed that the x has several components, not all are of them are $x$ as mentioned above. Below, type x[0], x[1], x[2], and x[3] and see what you get.

In [ ]:
# type x[0]-x[3], then type in r = np.dot(B,x[0])-b. Type r and see what you get;
# then type in rankB = np.linalg.matrix_rank(B) and see what you get
rankB = np.linalg.matrix_rank(B)
print(rankB)

3


# In class, we have discussed two systems being equivalent. This part solve the two systems and show you get the same solutions.

In class, we have discussed the two systems
\begin{align}
5x_1+10x_2-5x_3=5\\
2x_1-x_2+x_3=3\\
-x_1+2x_2+3x_3=7\end{align}

and

\begin{align}
x_1+2x_2-x_3=1\\
4x_2+2x_3=8\\
-5x_2+3x_3=1\end{align}

Now we will solve them with np.linalg.solve


In [ ]:
# run the following code and read the output. Explain the meaning of C, c, D, and d.

C = np.array([[5,-10,5],[2,-1,1],[-1,2,3]])
c = np.array([[5],[3],[7]])
solc = np.linalg.solve(C,c)

D = np.array([[1,2,-1],[0,4,2],[0,-5,3]])
d = np.array([[1],[8],[1]])
sold = np.linalg.solve(D,d)

print(solc, sold)

[[1.]
 [1.]
 [2.]] [[1.]
 [1.]
 [2.]]


# In class, we discussed the geometric meaning of $2\times 2$ systems. In this part, we will look at the geometric meaning of $3\times 3$ systems.

Consider the two linear equation $x_1- 2x_2 + x_3 = 0$ and $2x_2 - 8x_3 = 8$. We know they represent planes in 3D space. Run the following code.

In [ ]:
# run the following code, and make a comment to explain what this code means. Comments are made following a '#' sign.
# Update: if you have not taken tmath126 yet, you do not need to worry about this portion

n1 = (1,-2,1)
n2 = (0,2,-8)

d1 = 0
d2 = -8

def plotPlane(fig: go.Figure,
              normal: Tuple[int, int, int],
              d: int,
              values: Iterable,
              colorScaleName: str) -> None:
    """
        :param fig: figure to plot on
        :param colorScaleName: choose from <https://plotly.com/javascript/colorscales/>
    """
    # x, y, z
    x, y = np.meshgrid(values, values)
    z = (-normal[0] * x - normal[1] * y - d) * 1. / normal[2]

    # draw plane
    surface = go.Surface(x=x, y=y, z=z, colorscale=colorScaleName, showscale=False)
    fig.add_trace(surface, row=1, col=1)


# create figure
fig = make_subplots(rows=1, cols=1, specs=[[{'type': 'surface'}]])
# plot two intersectioned surfaces
values = range(-10, 11)
plotPlane(fig, n1, d1, values, "Hot")
plotPlane(fig, n2, d2, values, "phase")
fig.show()


# Generate a random matrix $A$ of $4\times 4$ and a vector $y$ of size $4\times 1$. Solve the system $(A|\mathbf{y})$ (or $Az=y$).

In [ ]:
# type in your codes here

A = np.random.randint(0, 59, (4,4))
y = np.random.randint(0, 6, (4,1))
soln = np.linalg.solve(A,y)