# In this lab, we investiagte several application of matrix computations. Complete the assignment by running existing code, typing your own code, or commenting on the code.

In [1]:
# import libraries
import numpy as np
from scipy.ndimage import gaussian_filter
from scipy.sparse import diags

import matplotlib.pyplot as plt
from PIL import Image



## We will look at some applications in computer vision of linear algebra.

In [2]:
# import image

face = Image.open("pexels_face.jpeg")

# show image

face.show()


Process image to get numpy arrays.

In [3]:
# color to grayscale
faceGray = face.convert('L')

# convert image file to array
faceArray = np.asarray(faceGray)

# check data size
faceShape = np.shape(faceArray)

print(faceShape) # check images size

(750, 500)


We cut the matrix into top and bottom half. Here we handle the image files using what we learned in block matrices.

In [4]:
topface = faceArray[0:375,]
bottomface = faceArray[375:,]

In [5]:
# show images of top and bottom face

top = Image.fromarray(topface, 'L')
top.show()

bottom = Image.fromarray(bottomface, 'L')
bottom.show()

Put the top and bottom images side by side. ($A|B$)

In [6]:
face2 = np.hstack((top,bottom))

face22 = Image.fromarray(face2, 'L')
face22.show()

In the following, insert cells. Type in your own code to cut the image vertically in two equal portions(call them, say leftface and rightface), then put them together in reverse order. Your new image should look like (rightface,leftface).

In [7]:
# insert your own code here

Check out this article on image classification: https://tinyurl.com/y4qommvo It seems like every single pixel counts in image recognition! In the following, we will alter a single pixel in the face image.

In [9]:
# alter pixel value at (300, 250)

# make a copy temp, who is not read-only file
temp = faceArray.copy()

print(temp[300,250])

# replace the value at (300,250) by 0

temp[300,250] = 0
temp = Image.fromarray(temp,'L')
temp.show()

93


You probably didn't see a difference in the image--this is a HD image, which means it has a lot of pixels. Changing one is hard to see. In the following, insert your own code to set a block of the image value to 0. Start off by making a copy of the faceArray datum so you can modify the image.

In [10]:
# insert your code here

Image blurring is also done with matrix multiplication. It uses something called convolution. (see Kernel on Wikipedia). In the following, you will see an example of blur

In [11]:
temp1 = faceArray.copy()
a = np.arange(50, step=2).reshape((5,5))
face_filter = gaussian_filter(a, sigma=1)
result = gaussian_filter(temp1, sigma=5)
temp1 = Image.fromarray(temp1,'L')
result = Image.fromarray(result,'L')
temp1.show()
result.show()


Insert your own code to blur topface. Change the blur so the image is less blurry as the previous output.

## In the following, we investigate block matrices in matrix computations.

In [12]:
# generate two integer valued matrices. Specify the values of m, n, and r. Then run the code

A = np.random.randint(5,size = (m,n))
B = np.random.randint(8,size = (n,r))

print(A,B)

NameError: name 'm' is not defined

In [13]:
# Do matrix computation with the full matrix. Read the product matrix.

product = np.dot(A,B)
product

NameError: name 'A' is not defined

In [14]:
# Compute the product of A and the firts column of B. Run the code and read the result.

product1 = np.dot(A,B[:,0])
product1

NameError: name 'A' is not defined

Compare the first column of product and product1. Type in your own code to compute their difference.

## In the following, we will study matrix division (or the more fancy name, inverse matrices). 

A lot of physical phenomena can be modeled by partial differential equation, then solved by numerical methods, very often by solving linear systems. Parabolic equations (describes heat diffusion) for example, are often tridiagonal systems. 

In [15]:
# run the code and print coeff
coeff = diags([1, -2, 1], [-1, 0, 1], shape=(7, 7)).toarray()
print(coeff)

[[-2.  1.  0.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.  0.  0.]
 [ 0.  1. -2.  1.  0.  0.  0.]
 [ 0.  0.  1. -2.  1.  0.  0.]
 [ 0.  0.  0.  1. -2.  1.  0.]
 [ 0.  0.  0.  0.  1. -2.  1.]
 [ 0.  0.  0.  0.  0.  1. -2.]]


You will see that most of the elements in your matrix are 0's. We call this type of matrix *sparse*. This particular matrix coeff has an inverse, we will compute the inverse below.

In [16]:
coeff_inv = np.linalg.inv(coeff)
coeff_inv

array([[-0.875, -0.75 , -0.625, -0.5  , -0.375, -0.25 , -0.125],
       [-0.75 , -1.5  , -1.25 , -1.   , -0.75 , -0.5  , -0.25 ],
       [-0.625, -1.25 , -1.875, -1.5  , -1.125, -0.75 , -0.375],
       [-0.5  , -1.   , -1.5  , -2.   , -1.5  , -1.   , -0.5  ],
       [-0.375, -0.75 , -1.125, -1.5  , -1.875, -1.25 , -0.625],
       [-0.25 , -0.5  , -0.75 , -1.   , -1.25 , -1.5  , -0.75 ],
       [-0.125, -0.25 , -0.375, -0.5  , -0.625, -0.75 , -0.875]])

Is the inverse matrix coeff_inv still sparse, i.e., does it have a lot of zeros? Ans:

In practice, when solving a system like $A\mathbf{x}=\mathbf{b}$ when $A$ is sparse, we often do not use $\mathbf{x}=A^{-1}\mathbf{b}$, as the computation is massive. 

In the following, we show an example for the claim *If $A$ is symmetric and invertible, then $A^{-1}$ is also symmetric*. 

In [17]:
# generate a random symmetric matrix with integer entries
Agen = np.random.randint(9,size = (8,8))
Asy = (Agen + Agen.T)/2

In [18]:
print(Asy)

[[2.  5.  2.  3.5 2.5 3.5 7.5 4. ]
 [5.  6.  4.  3.  1.5 7.5 3.  2. ]
 [2.  4.  1.  4.  4.5 5.  4.5 4. ]
 [3.5 3.  4.  0.  4.  3.  6.  2.5]
 [2.5 1.5 4.5 4.  5.  2.5 6.5 5.5]
 [3.5 7.5 5.  3.  2.5 1.  8.  3. ]
 [7.5 3.  4.5 6.  6.5 8.  4.  3. ]
 [4.  2.  4.  2.5 5.5 3.  3.  4. ]]


In [19]:
# Check if the matrix is invertible by running the code. rA computes the rank of matrix A, we will soon learn about it.
# If rA = order of matrix (for us, the order is 8), then the matrix is invertible; if rA < 8, generate another one.

rA = np.linalg.matrix_rank(Asy)
print(rA)

8


In [20]:
# When your Asymmetric is invertible, run the following code to compute the inverse. 
Asyinv = np.linalg.inv(Asy)


In the following cell, type your own code to justify *$A^{-1}$ is also symmetric*.

In [21]:
# type your own code

## We will play with generating block matrices and the identity matrices in this part

The command np.eye(n) generates the identity matrix of order n.

In [22]:
# define a 4 by 4 identity matrix. Run the code to print the matrix

B = np.eye(4)

print(B)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
# build a block matrix with B. We have seen np.zeros((m,n)), which generates a m by n zero matrix.

M = np.block([[np.zeros((4,4)),B], [B, np.zeros((4,4))]])

print(M)

[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


In [24]:
# Type your own code to compute the inverse of M. 



In [25]:
# build a block matrix with B and a random matrix. 

N = np.block([[B, np.zeros((4,4))], [np.random.randint(7,size = (4,4)), B]])

print(N)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 6. 2. 1. 1. 0. 0. 0.]
 [3. 1. 2. 1. 0. 1. 0. 0.]
 [2. 4. 1. 6. 0. 0. 1. 0.]
 [6. 5. 4. 4. 0. 0. 0. 1.]]


In [26]:
Ninv = np.linalg.inv(N)
print(Ninv)

[[ 1.00000000e+00 -2.96059473e-16  0.00000000e+00  5.55111512e-17
  -1.38777878e-17  0.00000000e+00  1.06010879e-17 -1.56713993e-17]
 [ 8.59551728e-17  1.00000000e+00  0.00000000e+00  1.11022302e-16
   0.00000000e+00  0.00000000e+00 -1.27213055e-17  2.83000235e-18]
 [-5.55111512e-17  4.27435864e-16  1.00000000e+00 -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00 -0.00000000e+00  5.55111512e-18]
 [-2.30695693e-17  1.32650024e-16  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.44184808e-17]
 [-3.81639165e-16 -6.00000000e+00 -2.00000000e+00 -1.00000000e+00
   1.00000000e+00 -0.00000000e+00  7.63278329e-17 -4.25007252e-17]
 [-3.00000000e+00 -1.00000000e+00 -2.00000000e+00 -1.00000000e+00
   4.16333634e-17  1.00000000e+00  0.00000000e+00 -9.71445147e-17]
 [-2.00000000e+00 -4.00000000e+00 -1.00000000e+00 -6.00000000e+00
   2.77555756e-17 -0.00000000e+00  1.00000000e+00 -6.47630098e-17]
 [-6.00000000e+00 -5.00000000e+00 -4.00000000e+00 -4.00000000e+00
   