# In this notebook, we see some examples of rectangular matrices and some matrix decomposition methods.

In [42]:
# import packages and print software information
import platform
import numpy as np
import scipy as sp
from matplotlib import pyplot as plt 
%matplotlib inline

import sys
print("Python 3 version is", sys.version)
import matplotlib
print("Matplotlib version is", matplotlib.__version__)
print("Numpy version is", np.__version__)
print("Scipy version is", sp.__version__)

print("System information: ", platform.uname())

Python 3 version is 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]
Matplotlib version is 3.5.1
Numpy version is 1.22.3
Scipy version is 1.8.0
System information:  uname_result(system='Linux', node='yajun-ThinkPad-T490s', release='5.4.0-131-generic', version='#147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022', machine='x86_64', processor='x86_64')


In [43]:
# Generate a random rectangular matrix
A = np.random.random((5,3))
print(A)

b = np.random.random((5,1))

[[0.4555097  0.1114864  0.4925508 ]
 [0.78887701 0.5797165  0.88716919]
 [0.39729365 0.80098053 0.45245641]
 [0.24393603 0.26720208 0.47606591]
 [0.9104574  0.55662203 0.34581534]]


## Rectangular matrices don't have inverse, but we can compute their (Moore-Penrose) pseudo-inverse. 

The pseudo-inverse of a matrix $A$, denoted $A^+$, is defined as: “the matrix that ‘solves’ the least square problem  $Ax=b$” i.e., if $\bar{x}$ is said solution, then $A^+$ is that matrix such that $\bar{x}=A^+b$.

The solution will be the same as the result of np.linalg.lstsq(A,b).

In [44]:
B = np.linalg.pinv(A)
x1 = B.dot(b)
x2, _, _, _ = np.linalg.lstsq(A,b)

print(x1)
print(x2)

[[ 0.10774517]
 [-0.35546051]
 [ 0.73493489]]
[[ 0.10774517]
 [-0.35546051]
 [ 0.73493489]]


/tmp/ipykernel_364416/115636695.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x2, _, _, _ = np.linalg.lstsq(A,b)


## The LU decomposition is implemented in the scipy library. 

In [45]:
A = np.random.random((4,4))

P, L, U = sp.linalg.lu(A)
print("Lower triangular matrix with 1 on the diagonal", L)
print("Upper triangular matrix", U)

print("Compute the difference between PLU-A", P.dot(L.dot(U))-A)

Lower triangular matrix with 1 on the diagonal [[ 1.          0.          0.          0.        ]
 [ 0.0071836   1.          0.          0.        ]
 [ 0.4381684  -0.13680297  1.          0.        ]
 [ 0.957973   -0.12015186  0.77141385  1.        ]]
Upper triangular matrix [[ 0.87144324  0.96702124  0.42466733  0.54387703]
 [ 0.          0.72203196  0.64021353  0.65809059]
 [ 0.          0.          0.83336421  0.32358471]
 [ 0.          0.          0.         -0.48402128]]
Compute the difference between PLU-A [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11022302e-16  0.00000000e+00]]
