<a href="https://colab.research.google.com/github/yajuna/tmath308/blob/master/Week8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we look at the last topic this quarter, the Eigen Stuff.

Eigen is German for characteristic or intrinsic, so eigenvalues and eigenvectors are characteristic values and vectors for a matrix. Matrix multiplication is linear transformation for vectors, and characteristic vectors are the vectors that do not change direction under these linear transformations. Notice the zero vector will always remain zero, so we exclude it while defining characteristic vectors.


## Definition (eigenvalues and eigenvectors)
Let $A$ be an $n\times n$ matrix. A scalar $\lambda$ is called an eigenvalue of $A$ if there is a _nonzero_ vector $\mathbf{x}$ such that $A\mathbf{x}=\lambda\mathbf{x}$.

$A\mathbf{x}=\lambda\mathbf{x}$ is equivalent to the linear system $(A-\lambda\mathbf{I})\mathbf{x}=\mathbf{0}$, and we look for non-zero solutions to this system. Generally, we need to find first all eigenvalues $\lambda_1,...,\lambda_k$ (in Section 4.2), then for each eigenvalue, we solve the homogeneous system and find _all_ corresponding eigenvectors. This is effectively finding the null space of $A-\lambda\mathbf{I}$.

A matrix can have repeated eigenvalues- the identity matrix (of $n\times n$) only has 1 as its eigenvalue. We group all the eigenvectors corresponding to the same values together.

## Definition (eigenspace)
Let $A$ be an $n\times n$ matrix, and let $\lambda$ be an eigenvalue of $A$. The collection of all eigenvectors corresponding to $\lambda$, together with the zero vector, is called the _eigenspace_ of $\lambda$, and is denoted by $E_{\lambda}$.

A very useful idea in mathematics is to cut big 'spaces' into small bite size spaces and study these small pieces one by one. Eigenspace is one such example.


The Numpy library can find eigenstuff with ``numpy.linalg.eig``. We see some examples here.

In [1]:
## Find eigen stuff with numpy
import numpy as np
A = np.random.rand(5,5)
evalues, evectors = np.linalg.eig(A)

print('Matrix \n', A,'\n')

print('eigenvalues \n', evalues,'\n')

print('eigenvectors \n', evectors,'\n')

Matrix 
 [[0.1801427  0.61771923 0.2582053  0.10030257 0.03977503]
 [0.9346804  0.92417418 0.87710264 0.12060495 0.24140184]
 [0.48337427 0.13013255 0.27515185 0.51147999 0.60618269]
 [0.45412518 0.85080319 0.25902494 0.02551751 0.54970446]
 [0.67417135 0.16700349 0.63648718 0.6684394  0.30359281]] 

eigenvalues 
 [ 2.16191539 -0.38414876 -0.22777288  0.12351147  0.03507384] 

eigenvectors 
 [[ 0.27098733 -0.3411155  -0.74579306  0.52104365  0.57842409]
 [ 0.60664863  0.15108961  0.24891475  0.23233831  0.14486636]
 [ 0.38040255  0.19827294  0.45987787 -0.66892514 -0.68499883]
 [ 0.46081414  0.70437185  0.38005268  0.17300773  0.18375915]
 [ 0.44887363 -0.57040362 -0.16095483 -0.44400441 -0.37609638]] 



In [7]:
i = 0

# compute A * v - lambd * v
residual = A.dot(evectors[:,i]) - evalues[i] * evectors[:,i]

print(evalues[i])

print(evectors[:,i])

print(residual)

2.161915393828133
[0.27098733 0.60664863 0.38040255 0.46081414 0.44887363]
[-3.33066907e-16 -8.88178420e-16  1.11022302e-16 -3.33066907e-16
 -1.44328993e-15]


## We see that to find eigenstuff for a matrix, we need to find all eigenvalues first.

From the definition of eigenvalues, we look for a scalar $\lambda$ such that there is a _nonzero_ vector $\mathbf{x}$ where $(A-\lambda\mathbf{I})\mathbf{x}=\mathbf{0}$. This means, eigenvalues will make the matrix $(A-\lambda\mathbf{I})$ singular (non invertible). For this, we introduce the idea of _determinant_ for square matrices.

## Definition (determinant)
Let $A$ be an $n\times n$ matrix. The determinant of $A$ is the _scalar_ defined recursively below:

$\det A=\sum^n_{j=1}(-1)^{1+j}a_{1j}\det A_{1j}=\sum^n_{j=1}a_{1j}C_{1j}$

where $C_{1j}=(-1)^{1+j}\det A_{1j}$ is called the _cofactor_ of $A$.

This is called the cofactor expansion definition. Note that the expansion was given along the first row, but Theorem 4.1 states that the expansions is valid for all rows or columns.

## Thm 4.1 (Laplace Expansion)
$\det A=\sum^n_{j=1}(-1)^{i+j}a_{ij}\det A_{ij}=\sum^n_{j=1}a_{ij}C_{ij}$

Ex. Expansion along the first column or first row shows that the determinant of a triangular matrix is the product of its diagonal elements.

Properties of determinants can be found from Theorem 4.3 to Theorem 4.14. We will focus on Theorem 4.6 as it helps with our eigen problem.

## Thm 4.6 (Invertibility vs determinant)
A square matrix $A$ is invertible if and only if $\det A\neq 0$.


As eigenvalues will make the matrix $(A-\lambda\mathbf{I})$ non invertible, we solve for $\lambda$ by setting $\det (A-\lambda\mathbf{I})=0$

## Determinants can be computed from the Numpy function ``numpy.linalg.det``. One application is to see if a system is uniquely solvable by checking the determinant of the coefficient matrix; nowadays we use the conditional number more.

In [ ]:
import numpy as np
A = np.random.rand(5,5)

det = np.linalg.det(A)

condNum = np.linalg.cond(A)

print(det, condNum)

0.052219772558896524 20.422860418462342


## Try to write some Python code to help you understand the properties listed in your book.

The following is to help see an example of $\det(AB)=\det(A)\det(B)$.

In [9]:
n = 15
A = np.random.rand(n,n)
B = np.random.rand(n,n)

# compute det(AB) - det(A) * det(B)
diff = np.linalg.det(A.dot(B)) - np.linalg.det(A) * np.linalg.det(B)

print(diff)

-2.5478751053409354e-17


# WE have outlined the eigen problem for a $n\times n$ matrix $A$.

We look for nonzero vector $\mathbf{x}$ and scalars $\lambda$ such that $A\mathbf{x} = \lambda\mathbf{x}$. This converts to a $n\times n$ homogeneous system $(A-\lambda I)\mathbf{x} = \mathbf{0}$, where we solve for nonzero $\mathbf{x}$ (finding the null space of $\lambda$) after finding the value $\lambda$.

$\lambda$'s are found by computing the equation $\det(A-\lambda I)=0$. The equation is a degree $n$ polynomial of $\lambda$ so we will be finding $n$ values.

## Definition (multiplicity of eiganvalues)

- Algebriac: the multiplicity of eigenvalue as a root of the characteristic polynomial

- Geometric: the dimension of $E_{\lambda}$. It is also the dimension of the null space of $A-\lambda I$, or the number of free variables of the homogeneous system.

In [13]:
## Example 4.18
import numpy as np
A = np.array(([0,1,0],[0,0,1],[2,-5,4]))

print(A[0,:])

evalueA, evectorA = np.linalg.eig(A)

print(evalueA, '\n', evectorA)

# Notice numpy does not see eigenspace

[0 1 0]
[1.00000001 0.99999999 2.        ] 
 [[-0.57735026  0.57735028 -0.21821789]
 [-0.57735027  0.57735027 -0.43643578]
 [-0.57735028  0.57735026 -0.87287156]]


In [23]:
# Check A * x - lambd * x

res1 = A.dot(evectorA[:,0]) - evalueA[0] * evectorA[:,0]

res11 = A.dot(evectorA[:,1]) - evalueA[1] * evectorA[:,1]

res2 = A.dot(evectorA[:,-1]) - evalueA[-1] * evectorA[:,-1]

print(res1, res2, res11)

[6.66133815e-16 4.44089210e-16 2.22044605e-16] [ 1.33226763e-15  4.44089210e-16 -8.88178420e-16] [-6.66133815e-16 -5.55111512e-16 -2.22044605e-16]


## Properties of eigenvalues
1. Eigenvalues of triangular matrices are the entries on its main diagonal
2. $A$ is invertible if and only if 0 is __not__ an eigenvalue of $A$.
3. If $A$ is invertible with $\lambda$ as an eigenvalue, and $\mathbf{x}$ an corresponding eigenvector, then $1/\lambda$ is an eigenvalue of $A^{-1}$, and $\mathbf{x}$ an corresponding eigenvector.
4. Eigenvectors for distinct eigenvalues are linearly independent.

In [33]:
import numpy as np

A = np.random.rand(4,4)

evalues, evectors = np.linalg.eig(A)

# Check that A^n x = lambd ^n x

n = 5
i = 0
res = np.linalg.matrix_power(A, n).dot(evectors[:,i]) - (evalues[i] ** n) * evectors[:,i]
print(res)

# try with n = 500 and you will see a very big error

[1.35003120e-13+0.j 4.08562073e-14+0.j 9.23705556e-14+0.j
 1.20792265e-13+0.j]


### Below we see an example of eigenvectors for distinct eigenvalues are lienarly independent.

In [37]:
A = np.diag([1, 2, 3])

eval, evec = np.linalg.eig(A)

print(np.linalg.det(evec))

1.0


## In Chapter 2 we studies a type of equivalence relation between matrices (row equivalence), this section introduces another.

### Definition (similarity)
Let $A$ and $B$ be $n\times n$ matrices. We say $A$ is similar to $B$ if there is an invertible $n\times n$ matrix $P$ such that $P^{-1}AP=B$. We write $A\sim B$.

Note: equivalence relations are reflective, symmetric, and transitive.

### Definition (diagonalizable)
Matrix $A$ is diagonalizable if it is similar to a diagonal matrix. $A$ is diagonalizable if and only if it has $n$ linearly indepdent eigenvectors. Then $D$ is composed of corresponding eigenvalues at the main diagonal.