<a href="https://colab.research.google.com/github/yajuna/tmath308/blob/master/Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This week, we go over Sections 3.2 and 3.3, and study matrix computation/algebra more. A lot of properties that you 'expect' to be true (properties for scalars) are still true for matrices, but there are certain things that differ- those are mostly due to the differences between scalars and arrays. Some examples include multiplication, transpose, and inverse.

There is a difference between matrix arithmetic and matrix algebra-

- arithemtic studies matrices entry-wise. We zoom in and see how the computations are done.

- algebra studies matrices as a whole. We zoom out and study relations between matrices without worrying what is going on within each matrix in details.

## Algebraic properties of matrix addtion and scalar multiplication
Let $A$, $B$, and $C$ be matrices of _the same size_, and $c$, $d$ be scalars. Then
- $A+B=B+A$
- $(A+B)+C=A+(B+C)$
- $A+O=A$
- $A+(-A)=O$
- $c(A+B)=cA+cB$
- $(c+d)A=cA+dA$
- $c(dA)=(cd)A$
- $1A=A$

These calculations are done based on our definition from Section 3.1. For example, $A+B$ is computed by adding the corresponding entries $a_{ij}+b_{ij}$.

These properties are easily justified with the Numpy libarary, so please play with Python a little to try.

They are also the 8 axioms for something more general called _vector spaces_. We will look at more general vector spaces in Chapter 6.

In [1]:
import numpy as np
import scipy as sp
import matplotlib
from matplotlib import pyplot as plt

In [2]:
m,n = 6,5
min, max = -3,7
c,d = 2,3
A = np.random.randint(min, max, (m,n))
B = np.random.randint(min, max, (m,n))
C = np.random.randint(min, max, (m,n))
O = np.zeros((m,n))

print(c,d,A,B,C,O)

2 3 [[ 3 -1  6  2  0]
 [ 4  2  6  6  2]
 [-1 -2 -2  2 -1]
 [ 1 -2  1  4  1]
 [ 5 -1  3 -2  1]
 [-1  2  3  2  6]] [[ 5  3  6  5 -2]
 [-3 -3  6  3  2]
 [ 5  1 -2 -1  5]
 [-2  2 -3  2  6]
 [ 0  1  6  3  4]
 [-2 -1  3  5  3]] [[ 0  4  4 -1  1]
 [ 5  6 -1  1  0]
 [ 4  5  4 -2  2]
 [ 2  2 -2 -3 -2]
 [ 6  3 -3  4  6]
 [ 5 -1  6  2  4]] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Just like vectors, we can linearly combine matrices.

With coefficients $c_1,...,c_n$, the linear combination of matrices (of the same size) $A_1,...,A_n$ is

$c_1A_1+...+c_nA_n$.

(Linear combination is just fancy weighted sum.)

Linear dependence and independence can also be generalized to matrices as well:

- $A_1,...,A_n$ are linearly independent if the only solution to

$c_1A_1+...+c_nA_n=O$

is the trivial one $c_1=...=c_n=0$;

- If there are nontrivial coefficients that satisfy

$c_1A_1+...+c_nA_n=O$,

then we say $A_1,...,A_n$ are linearly dependent.

A notion similar to span and spanning set can also be defined, and we can talk about matrices of size $m\times n$ spanning $\mathbb{R}^{m\times n}$.

## We look at properties of matrix multiplication, and transpose.

### Matrix multiplication- $A$, $B$, $C$ are matrices of proper sizes for multiplication, and $k$ a scalar.

- $A(BC)=A(BC)$
- $A(B+C)=AB+AC$
- $(A+B)C=AC+BC$
- $k(AB)=(kA)B=A(kB)$
- $I_mA=A=AI_n$ for $A$ of size $m\times n$

### Tranpose

- $(A^T)^T=A$
- $(A+B)^T=A^T+B^T$
- $(kA)^T=k(A^T)$
- $(AB)^T=B^TA^T$
- $(A^r)^T=(A^T)^r$, $r\in \mathbb{Z}^{+}$.


We see some computational examples

In [3]:
matrix = []
for j in range(5):
  matrix.append(np.random.randint(min, max, (m,n)))

# print(matrix)

In [4]:
AA = sum(matrix)

print(AA)
print(AA.transpose())

[[10 12 16  6 13]
 [ 9  3  5 13 14]
 [ 9 10  6  9  6]
 [-6  9  8  5  2]
 [10  8  2  8  5]
 [12  2 19 -2  8]]
[[10  9  9 -6 10 12]
 [12  3 10  9  8  2]
 [16  5  6  8  2 19]
 [ 6 13  9  5  8 -2]
 [13 14  6  2  5  8]]


In [5]:
BB = np.zeros((m,n)).transpose()
for A in matrix:
  BB += A.transpose()

print(BB)

[[10.  9.  9. -6. 10. 12.]
 [12.  3. 10.  9.  8.  2.]
 [16.  5.  6.  8.  2. 19.]
 [ 6. 13.  9.  5.  8. -2.]
 [13. 14.  6.  2.  5.  8.]]


### Write a snippet to justify the following results

__Theorem__

a. If $A$ is a square matrix, then $A+A^T$ is a symmetric matrix.

b. For any matrix $A$, $AA^T$ and $A^TA$ are symmetric matrices.

## In Section 3.3, we study "division" of (square) matrices.

Similar to scalars, there is a notion of "divisibility"- a number that is non zero is similar to a matrix that is non singular.

The reciprical of a scalar is generalized to an inverse of a matrix.

A scalar and its reciprical multiply to be 1; a matrix and its inverse multiply to be the identity matrix.

### Definition (inverse)
If $A$ is an $n\times n$ matrix, an __inverse__ of $A$ is an $n\times n$ matrix $A^{-1}$ with the property that

$AA^{-1}=I$ and $A^{-1}A=I$

where $I=I_n$ is the $n\times n$ identity matrix. If such $A^{-1}$ exists, then $A$ is called __invertible__.

Note: your book uses a different notation $A'$ for the inverse until page 164.

### Theorem (Uniqueness of inverse)
If $A$ is invertible, then its inverse is unique.

### Theorem (Invertible coefficient matrix implies unique solution)
If $A$ is an invertible $n\times n$ matrix, then the system of linear equations given by $A\mathbf{x}=\mathbf{b}$ has the unique solution $\mathbf{x}=A^{-1}\mathbf{b}$ for any $\mathbf{b}$ in $\mathbb{R}^n$.

### Properties of inverse matrices

- If $A=\begin{pmatrix}a&b\\c&d\end{pmatrix}$, $2\times 2$ is invertible, then $A^{-1}=\frac{1}{ad-bc}\begin{pmatrix}d&-b\\-c&a\end{pmatrix}$.

- Inverse of $A^{-1}$ is $A$.

- If $A$ is invertible and $c$ is non zero, then $(cA)^{-1}=\frac{1}{c}A^{-1}$.

- If $A$ and $B$ are invertible and of the same size. Then $AB$ is invertible and $(AB)^{-1}=B^{-1}A^{-1}$.

- If $A$ is invertible, then $(A^T)^{-1}=(A^{-1})^T$.

- If $A$ is invertible, then $(A^n)^{-1}=(A^{-1})^n$.

- Elementary matrices are invertible; their inverses are of the same type.

- Left inverse is right inverse: Let $A$ be a square matrix. If $B$ is a square matrix such that either $AB=I$ or $BA=I$, then $A$ is invertible and $B=A^{-1}$.


In [6]:
# Test the above computations with Numpy.

### Theorem (Fun. Thm. of Invertible Matrices. v1)
Let $A$ be $n\times n$. The following are equivalent:

a. $A$ is invertible.

b. $A\mathbf{x}=\mathbf{b}$ has a unique solution for every $\mathbf{b}$ in $\mathbb{R}^n$.

c. $A\mathbf{x}=\mathbf{0}$ has only the trivial solution.

d. The REF of $A$ is $I_n$.

e. $A$ is a product of elementary matrices.

## Theorem (Left inverse and right inverse are the inverse)
Let $A$ be a square matrix. If $B$ is a square matrix such that either $AB=I$ or $BA=I$, then $A$ is invertible and $B=A^{-1}$.

Note: from now on, you will only need to find either the left or the right inverse.