<a href="https://colab.research.google.com/github/yajuna/tmath308/blob/master/Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This week, we go over Sections 3.2 and 3.3, and study matrix computation/algebra more. A lot of properties that you 'expect' to be true (properties for scalars) are still true for matrices, but there are certain things that differ- those are mostly due to the differences between scalars and arrays. Some examples include multiplication, transpose, and inverse.

## Algebraic properties of matrix addtion and scalar multiplication
Let $A$, $B$, and $C$ be matrices of _the same size_, and $c$, $d$ be scalars. Then
- $A+B=B+A$
- $(A+B)+C=A+(B+C)$
- $A+O=A$
- $A+(-A)=O$
- $c(A+B)=cA+cB$
- $(c+d)A=cA+dA$
- $c(dA)=(cd)A$
- $1A=A$

These calculations are done element-wise. For example, $A+B$ is computed by adding the corresponding entries $a_{ij}+b_{ij}$.

Therefore, these properties are easily justified with the Numpy libarary, so please play with Python a little to try.

In [1]:
import numpy as np
import scipy as sp
import matplotlib
from matplotlib import pyplot as plt

In [2]:
m,n = 6,5
min, max = -3,7
c,d = 2,3
A = np.random.randint(min, max, (m,n))
B = np.random.randint(min, max, (m,n))
C = np.random.randint(min, max, (m,n))
O = np.zeros((m,n))

print(c,d,A,B,C,O)

2 3 [[ 0  4  6  0 -3]
 [ 3  1  2  3 -1]
 [-2  0  0  6  2]
 [ 1  6  5  0  1]
 [ 1 -3  2  0 -3]
 [ 3  3  4  2  1]] [[ 0 -1  6  2 -2]
 [-3  3 -1 -1  1]
 [ 2  4  3 -2  3]
 [ 0  0  1 -2  5]
 [-1  3 -1  6  2]
 [ 6 -3 -2  0 -2]] [[-3 -3  6  3  6]
 [ 0  2  2  0  3]
 [-1  0  1 -3  6]
 [-2  3 -3  1  2]
 [ 6  3 -1  3  6]
 [ 3 -3  1 -2  6]] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Just like vectors, we can linearly combine matrices.

With coefficients $c_1,...,c_n$, the linear combination of matrices (of the same size) $A_1,...,A_n$ is

$c_1A_1+...+c_nA_n$.

(Linear combination is just fancy weighted sum.)

Linear dependence and independence can also be generalized to matrices as well:

- $A_1,...,A_n$ are linearly independent if the only solution to

$c_1A_1+...+c_nA_n=O$

is the trivial one $c_1=...=c_n=0$;

- If there are nontrivial coefficients that satisfy

$c_1A_1+...+c_nA_n=O$,

then we say $A_1,...,A_n$ are linearly dependent.

A notion similar to span and spanning set can also be defined, and we can talk about matrices of size $m\times n$ spanning $\mathbb{R}^{m\times n}$.

## We look at properties of matrix multiplication, and transpose.

### Matrix multiplication- $A$, $B$, $C$ are matrices of proper sizes for multiplication, and $k$ a scalar.

- $A(BC)=A(BC)$
- $A(B+C)=AB+AC$
- $(A+B)C=AC+BC$
- $k(AB)=(kA)B=A(kB)$
- $I_mA=A=AI_n$ for $A$ of size $m\times n$

### Tranpose

- $(A^T)^T=A$
- $(A+B)^T=A^T+B^T$
- $(kA)^T=k(A^T)$
- $(AB)^T=B^TA^T$
- $(A^r)^T=(A^T)^r$, $r\in \mathbb{Z}^{+}$.


We see some computational examples

In [5]:
matrix = []
for j in range(5):
  matrix.append(np.random.randint(min, max, (m,n)))

# print(matrix)

In [9]:
AA = sum(matrix)

print(AA)
print(AA.transpose())

[[ 7 -1 10  7  4]
 [ 8 10  5  7 10]
 [10 10 16  1  7]
 [ 3 16 18  7  6]
 [10  4 10  9 -3]
 [-3 17  6 -2 16]]
[[ 7  8 10  3 10 -3]
 [-1 10 10 16  4 17]
 [10  5 16 18 10  6]
 [ 7  7  1  7  9 -2]
 [ 4 10  7  6 -3 16]]


In [11]:
BB = np.zeros((m,n)).transpose()
for A in matrix:
  BB += A.transpose()

print(BB)

[[ 7.  8. 10.  3. 10. -3.]
 [-1. 10. 10. 16.  4. 17.]
 [10.  5. 16. 18. 10.  6.]
 [ 7.  7.  1.  7.  9. -2.]
 [ 4. 10.  7.  6. -3. 16.]]


### Write a snippet to justify the following results

__Theorem__

a. If $A$ is a square matrix, then $A+A^T$ is a symmetric matrix.

b. For any matrix $A$, $AA^T$ and $A^TA$ are symmetric matrices.

## In Section 3.3, we study "division" of (square) matrices.

Similar to scalars, there is a notion of "divisibility"- a number that is non zero is similar to a matrix that is non singular.

The reciprical of a scalar is generalized to an inverse of a matrix.

A scalar and its reciprical multiply to be 1; a matrix and its inverse multiply to be the identity matrix.

### Definition (inverse)
If $A$ is an $n\times n$ matrix, an __inverse__ of $A$ is an $n\times n$ matrix $A^{-1}$ with the property that

$AA^{-1}=I$ and $A^{-1}A=I$

where $I=I_n$ is the $n\times n$ identity matrix. If such $A^{-1}$ exists, then $A$ is called __invertible__.

Note: your book uses a different notation $A'$ for the inverse until page 164.

### Theorem (Uniqueness of inverse)
If $A$ is invertible, then its inverse is unique.

### Theorem (Invertible coefficient matrix implies unique solution)
If $A$ is an invertible $n\times n$ matrix, then the system of linear equations given by $A\mathbf{x}=\mathbf{b}$ has the unique solution $\mathbf{x}=A^{-1}\mathbf{b}$ for any $\mathbf{b}$ in $\mathbb{R}^n$.

### Properties of inverse matrices

- If $A=\begin{pmatrix}a&b\\c&d\end{pmatrix}$, $2\times 2$ is invertible, then $A^{-1}=\frac{1}{ad-bc}\begin{pmatrix}d&-b\\-c&a\end{pmatrix}$.

- Inverse of $A^{-1}$ is $A$.

- If $A$ is invertible and $c$ is non zero, then $(cA)^{-1}=\frac{1}{c}A^{-1}$.

- If $A$ and $B$ are invertible and of the same size. Then $AB$ is invertible and $(AB)^{-1}=B^{-1}A^{-1}$.

- If $A$ is invertible, then $(A^T)^{-1}=(A^{-1})^T$.

- If $A$ is invertible, then $(A^n)^{-1}=(A^{-1})^n$.

- Elementary matrices are invertible; their inverses are of the same type.

- Left inverse is right inverse: Let $A$ be a square matrix. If $B$ is a square matrix such that either $AB=I$ or $BA=I$, then $A$ is invertible and $B=A^{-1}$.


In [ ]:
# Test the above computations with Numpy.

### Theorem (Fun. Thm. of Invertible Matrices. v1)
Let $A$ be $n\times n$. The following are equivalent:

a. $A$ is invertible.

b. $A\mathbf{x}=\mathbf{b}$ has a unique solution for every $\mathbf{b}$ in $\mathbb{R}^n$.

c. $A\mathbf{x}=\mathbf{0}$ has only the trivial solution.

d. The REF of $A$ is $I_n$.

e. $A$ is a product of elementary matrices.