<a href="https://colab.research.google.com/github/yajuna/tmath308/blob/master/Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we look at Section 2.3, spanning sets, and linear independence. We will also introduce matrix operations (section 3.1). This is where linear algebra and modern computations are combined, and you get to see extremely powerful things.

In [1]:
import numpy as np
import scipy as sp
import matplotlib
from matplotlib import pyplot as plt

## Definition (linear combination)
Consider a set of vectors $\mathbf{u}_1$, $\mathbf{u}_2$,..., $\mathbf{u}_n$, and a vector $\mathbf{x}$. If there is a set of scalars $c_1,c_2,..., c_n$ such that

$\mathbf{x} = c_1\mathbf{u}_1+c_2\mathbf{u}_2+...+c_n\mathbf{u}_n$,

then we say $\mathbf{x}$ is a linear combination of $\mathbf{u}_1$, $\mathbf{u}_2$,..., $\mathbf{u}_n$.

Consider a linear system with augmented matrix $[A|\mathbf{b}]$. Denote the columns of $A$ by $\mathbf{a}_1$, $\mathbf{a}_2$,..., $\mathbf{a}_n$.

We look at the relationship between a system $A\mathbf{x}=\mathbf{b}$ and $\mathbf{b} = x_1\mathbf{a}_1+x_2\mathbf{a}_2+...+x_n\mathbf{a}_n$.



### Example
Consider system
$\begin{cases}2x-y = 3\\ x+y = 2\end{cases}$.

The augmented matrix is
$\left(\begin{array}{cc|c}  
 2 & -1 & 3\\  
 1 & 1 & 2  
\end{array}\right)$.

Solving by hand, we know the solution to this system is
$\mathbf{x}=\begin{pmatrix}5/3\\ 1/3\end{pmatrix}$

In [2]:
# define coefficient matrix and right hand side
A = np.array([[2, -1],[1, 1]])
b = np.array([3,2])

# solve with numpy
soln = np.linalg.solve(A,b)

In [3]:
# print the solution
print("Solution is", soln)

Solution is [1.66666667 0.33333333]


In the following we will see that $x_1\mathbf{a}_1+x_2\mathbf{a}_2=\mathbf{b}$.

Let `residual` = $\mathbf{b}-x_1\mathbf{a}_1-x_2\mathbf{a}_2$

In [6]:
residual = b - soln[0] * A[:,0] - soln[1] * A[:,1]
print("Solutions and columns of coefficient matrix\n", soln[0], soln[1], A[:,0], A[:,1])

print("The residual is\n", residual)

Solutions and columns of coefficient matrix
 1.6666666666666667 0.3333333333333333 [2 1] [-1  1]
The residual is
 [-1.66533454e-16 -5.55111512e-17]


## Theorem
A system of linear equations with augmented matrix $[A | \mathbf{b}]$ is consistent if and
only if $\mathbf{b}$ is a linear combination of the columns of $A$.

$\begin{cases}a_{11}x_1+a_{12}x_1+...+a_{1n}x_n=b_1\\
a_{21}x_1+a_{22}x_1+...+a_{2n}x_n=b_2\\
\dots\\
a_{m1}x_1+a_{m2}x_1+...+a_{mn}x_n=b_m\end{cases}$

You can think of the equations "vertically", and see it to be
$\begin{pmatrix}a_{11}\\ a_{21}\\\vdots\\ a_{m1}\end{pmatrix}x_1+\begin{pmatrix}a_{12}\\ a_{22}\\\vdots\\ a_{m2}\end{pmatrix}x_2+...+\begin{pmatrix}a_{1n}\\ a_{2n}\\\vdots\\ a_{mm}\end{pmatrix}x_n=\mathbf{b}$.

In [7]:
A = np.random.randint(-10, 10, (5,5))
b = np.random.randint(-10, 10, (5,1))
x = np.linalg.solve(A,b)
print(x)

[[  9.11903513]
 [ 33.63817514]
 [ -8.29575249]
 [-18.0844258 ]
 [ 17.70582066]]


### For a given coefficient matrix $A$ (the columns $\mathbf{a}_j$ are fixed), what kind of right hand side $b$'s make the system $(A|\mathbf{b})$ solvable?

## Definition
If $S = \{\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_k\}$ is a set of vectors in $\mathbb{R}^n$, then the set of all
linear combinations of $\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_k$ is called the _span_ of $\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_k$, and is denoted by span($S$) or span($\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_k$). If span($S$)$=\mathbb{R}^n$, then S is called a spaning set for $\mathbb{R}^n$.

So to show a set of vectors $\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_k$ is a spanning set for $\mathbb{R}^n$, we show that any vector in $\mathbb{R}^n$ can be written as a linear combination of them.

### Example
$\mathbb{R}^2$ is its own spanning set- every vector $\mathbf{x}$ is a linear combination of all vectors in $\mathbb{R}^2$: $\mathbf{x} = 1\cdot\mathbf{x}+0\cdot$ all other vectors; At least how many vectors do we need in a spanning set of $\mathbb{R}^2$?

## Definition (linear in/dependence)
A set of vectors $\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_k$ is _linearly dependent_ if there are scalars
$c_1,c_2,..., c_n$ at least one of which is _not zero_, such that

$c_1\mathbf{v}_1+c_2\mathbf{v}_2+ . . . +c_k\mathbf{v}_k=\mathbf{0}$.

A set of vectors is _linearly independent_, if

$c_1\mathbf{v}_1+c_2\mathbf{v}_2+ . . . +c_k\mathbf{v}_k=\mathbf{0}$

implies that all scalars $c_1,c_2,..., c_n$ must all equal 0.

### Example (Theorem)
If $\mathbf{x} = c_1\mathbf{u}_1+c_2\mathbf{u}_2+...+c_n\mathbf{u}_n$, then $\mathbf{x}, \mathbf{u}_1 , \mathbf{u}_2 , . . . , \mathbf{u}_n$ is _linearly dependent_. Why?

### Example
Any set of vectors containing the zero vector is linearly dependent. Why?

### Theorem
Let $\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_n$ be column vectors in $\mathbf{R}^m$ and $A=(\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_n)$ is a $m\times n$ matrix. Then $\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_n$ are _linearly dependent_ if and only if the system with augmented matrix $[A|\mathbf{0}]$ has a nontrivial solution.

So the system only a trivial solution if and only if the columns are _linearly independent_.

Note: For this theorem, my letters are the opposite of your textbook.

### Theorem
Let $\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_m$ be row vectors in $\mathbf{R}^n$ and $A=\begin{pmatrix}\mathbf{v}_1\\ \mathbf{v}_2 \\ \dots\\\mathbf{v}_m\end{pmatrix}$ is a $m\times n$ matrix. Then $\mathbf{v}_1 , \mathbf{v}_2 , . . . , \mathbf{v}_m$ are _linearly dependent_ if and only if rank$(A)<m$.

### Theorem
Any set of $n$ vectors in $\mathbb{R}^m$ with $n>m$ is linearly dependent.

This means any homogeneous linear system with coefficient matrix of shape $m\times n$ with $n>m$ will have a nontrivial solution.

# By now, we have seen the convenience brought by arrays of numbers- writing linear systems with matrices, representing matrices with columns or rows. So this chapter, we systematically study arrays of numbers, or matrices.

## Definition
A matrix is a rectangular array of numbers. The number at $i$-th row and $j$-the column is called the $(i,j)$ entry or element of the matrix. If the matrix is denoted by $A$, the $(i,j)$ element is denoted by $a_{ij}$.


Special matrices include:
- square matrix
- diagonal matrix
- identity matrix
- scalar matrix
- equal matrices

In [ ]:
# square matrix
A = np.random.randint(-10, 10, (5,5))
print("Square matrix of size 5 by 5\n", A)

# Make a diagonal matrix given diagonal elements
x = np.array([1,2,3])
B = np.diag(x)
print("Diagonal matrix with given elements\n", B)

# Make an identity matrix
I = np.eye(3)
print("Identity matrix\n", I)

# Make a scalar matrix where each diagonal element is pi
Pi = np.pi * I
print("Scalar matrix with pi on the diagonal\n", Pi)

Square matrix of size 5 by 5
 [[ -8   2 -10   6   2]
 [  5   0  -6   2   4]
 [ -1   7  -5  -6  -2]
 [ -1   5  -3   5  -6]
 [  5  -7  -5   0   7]]
Diagonal matrix with given elements
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Identity matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Scalar matrix with pi on the diagonal
 [[3.14159265 0.         0.        ]
 [0.         3.14159265 0.        ]
 [0.         0.         3.14159265]]


## Matrix addition (same size) and scalar multiplication

In [ ]:
A = np.random.randint(-5, 3, (4,3))
B = np.random.randint(7, 11, (4,3))
C = A + B
print("A=\n", A, "\n B=\n", B)
print(f"Sum C=\n {C}\n")

A=
 [[-2 -4 -4]
 [ 2 -1 -1]
 [-4 -3 -1]
 [-1 -4  0]] 
 B=
 [[ 7 10  7]
 [ 9  9  8]
 [10 10 10]
 [ 7  9  8]]
Sum C=
 [[ 5  6  3]
 [11  8  7]
 [ 6  7  9]
 [ 6  5  8]]



In [ ]:
# scalar multiplication
c = 0.5
cA = c * A
print("c times A\n", cA)

c times A
 [[-2.  -1.5  1. ]
 [-1.5 -1.   0. ]
 [ 1.  -1.  -1.5]
 [-1.   0.5 -1.5]]


## Matrix multiplication is a little tricky- it is explained perfectly by the diagram on your textbook on page 142.

## Definition (matrix multiplication)
$A$ is an $m\times n$ matrix and $B$ is an $n\times r$ matrix; then thier product $C=AB$ is an $m\times r$ matrix. The $(i,j)$-th entry of $C$ is computed by multiplying the $i$-th row of $A$ and $j$-th column of $B$.

Note: Matrix multiplications are generally __not__ commutative. That means in general $AB\neq BA$.

In [ ]:
# Matrix multiplication
m = 3
n = 5
r = 4
A = np.random.randint(-5, 2, (m,n))
B = np.random.randint(3, 7, (n,r))
C1 = np.matmul(A, B)
C2 = A @ B
C3 = A.dot(B)
print(f"Product by matmul\n{C1}\n")
print(f"Product by @\n{C2}\n")
print(f"Product by dot product\n{C3}\n")

print(f"type of C {type(C)}")

Product by matmul
[[-49 -66 -74 -66]
 [-30 -39 -42 -41]
 [-32 -35 -38 -39]]

Product by @
[[-49 -66 -74 -66]
 [-30 -39 -42 -41]
 [-32 -35 -38 -39]]

Product by dot product
[[-49 -66 -74 -66]
 [-30 -39 -42 -41]
 [-32 -35 -38 -39]]

type of C <class 'numpy.ndarray'>
